### ISSUE TITLE
Integração Google Groups

### ISSUE THREAD

**Issue by humrochagf** [pythonbrasil/wiki#10]
Adicionar uma página com um iframe para a lista de emails da python brasil

**Comment by humrochagf** [comment]
o @luzfcb já fez isso neste site:
http://dojoto.info/pages/about.html
com este código:
https://gist.github.com/luzfcb/5615e518718ff796fb97

E está convidado para ajudar com esta issue por livre e espontânea pressão :stuck_out_tongue_winking_eye:

**Comment by luzfcb** [comment]
já estava trabalhando nisso, já tenho quase tudo pronto... embora seja HTML..
meu problema atual é puramente design

**Comment by humrochagf** [comment]
taca lá do jeito que vc achar melhor que a gente vai ajustando, a ideia é essa mesmo. Contribuir com a parte que sabe que cada um complementa com seu know-how

**Comment by magnunleno** [comment]
Design vamos arrumando aos poucos @luzfcb. Qualquer contribuição já será bem vinda.

**Comment by humrochagf** [comment]
valeu cara
