### ISSUE TITLE
Adicionar Prêmio Dorneles ao menu Participe

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/wiki#101]
Atualmente o conteúdo já existe, apenas deve ser revisado:

https://github.com/pythonbrasil/wiki/blob/pelican/content/pages/premio-dorneles-tremea.md

E adicionado ao menu Participe

**Comment by humrochagf** [comment]
por ser um prêmio celebrado na python brasil, este conteúdo não deveria ficar junto com a página que fala da python brasil não?

**Comment by filipecifali** [comment]
Conversei com a @taniaa e concordamos que ficaria muito conteúdo na página da PythonBrasil (http://python.org.br/python-brasil)

**Comment by humrochagf** [comment]
saquei, vou deixar essa issue para o hour of code que a gente vai fazer na quinta feira por aqui, que é um bom exemplo de uso do pelican

**Comment by taniaa** [comment]
Ótima ideia, @humrochagf!

**Comment by humrochagf** [comment]
A @taniaa já passou fazendo a limpa na parte de conteúdo então vou tirar a tag de conteúdo

**Comment by taniaa** [comment]
Obrigada, Jéssica! (@jornalistadigital)
