### ISSUE TITLE
Construir automaticamente via travis e adicionar uma badge do status do travis no README

### ISSUE THREAD

**Issue by leorochael** [pythonbrasil/wiki#12]
Apesar do README dizer:

> Este projeto utiliza pelican como gerador de páginas estáticas e travis-ci para realizar a compilação.

Ainda não vi um `.travis.yml` na raiz do repositório (talvez não seja necessário, não sou o maior expert de travis ainda).

Seria ideal também se tivesse um badge do travis mostrando o status de construção.

Além disso, seria ideal se pull-requests fossem construídos pelo travis também para verificar se não tem nenhum erro (mas não mandados para github.io, claro).

**Comment by humrochagf** [comment]
sim, ainda não subi o travis pq a aprovação da integração está pendente pelos owners da organização

**Comment by humrochagf** [comment]
aeeew, consegui @leorochael vou dar continuidade aqui com a integração do travis e te mando um feedback quando finalizar

**Comment by humrochagf** [comment]
inclusive estou documentando este processo e vou publicar no blog do df.python.org.br para quem tiver interesse em fazer esta integração :smile:

**Comment by luzfcb** [comment]
caso seja de alguma ajuda: http://blog.ionelmc.ro/2015/07/11/publishing-to-github-pages-from-travis-ci/

**Comment by luzfcb** [comment]
no pythonclub eu fiz um pouco diferente disso ai, porque a 2 anos atras não havia deploy keys no github

**Comment by humrochagf** [comment]
ah, show de bola @luzfcb agiliza mais ainda

**Comment by leorochael** [comment]
@humrochagf, sugiro utilizar [deploy via script](https://docs.travis-ci.com/user/deployment/script), para fazer a parte do deploy pro gh-pages, mas só quando for o branch correto **e não** for um pull request (`condition: "$TRAVIS_PULL_REQUEST" = "false"`).

**Comment by luzfcb** [comment]
@leorochael basicamente é algo como este: https://github.com/pythonclub/pythonclub.github.io/blob/pelican/deploy.sh

a diferença é que, aparentemente utilizando o `ghp-import` vc não vai precisar dessas linhas https://github.com/pythonclub/pythonclub.github.io/blob/pelican/deploy.sh#L16-L25

**Comment by leorochael** [comment]
@luzfcb, sim, a outra diferença é que, usando `provider: script` e o `condition:` (e o `branch:`), vc pode tirar o `if` de dentro do script de deploy, o que eu acho mais limpo.

**Comment by humrochagf** [comment]
pronto, integrado com o travis :tada:

**Comment by leorochael** [comment]
@cadu-leite Pronto, acabou a desculpa para não usar o Pelican :-)
