### ISSUE TITLE
A seção "Integrantes da diretoria e conselhos" está desatualizada

### ISSUE THREAD

**Issue by muriloviana** [pythonbrasil/wiki#136]
Link da página: http://python.org.br/apyb

Para a resolução desta issue é necessário os nomes e cargos da nova diretoria e conselho.

**Comment by muriloviana** [comment]
A Diretoria eleita está composta da seguinte forma:

Presidente: Mário Sérgio Oliveira de Queiroz
Diretor Financeiro: Henrique dos Santos Bastos
Diretor de Tecnologia: Humberto Rocha Gonçalves Filho
Diretora de Marketing e Comunicação: Letícia Vasques dos Reis Portella Nascimento

O corpo do Conselho Deliberativo eleito:
Marco Antônio Rougeth
Jessica Caroline Alves Nunes Temporal
Erika Campos

O corpo do Conselho Fiscal eleito:
Leonardo Rochael
Renata Scheibler
Luis Felipe Miléo

Suplentes:
Tânia Andrea
Filipe Cifali Stangler

**Comment by humrochagf** [comment]
Merged, valeu galera

**Comment by rougeth** [comment]
Meu nome ta errado :/

**Comment by humrochagf** [comment]
Corrigido https://github.com/pythonbrasil/wiki/commit/c1904f1b2b9c612e9c62324ff48d8e53a5a6269e

**Comment by rougeth** [comment]
Você é de mais @humrochagf! o/

**Comment by humrochagf** [comment]
são seu olhos @rougeth
