### ISSUE TITLE
[Porto Alegre CLT] Python Sênior

### ISSUE THREAD

**Issue by micheltlutz** [pythonbrasil/wiki#174]
Estamos procurando uma pessoa desenvolvedora Python Sênior para trabalhar com as seguintes tecnologias:
Python 3
Django 2+
Django Rest Framework
JWT
Git / GitHub / GitFlow
TravisCI
AWS
O que podemos adiantar é que o ambiente é acolhedor, o time é divertido e estamos criando algo f * * *.
Mais Detalhes em https://github.com/cingulo/vagas

**Comment by luzfcb** [comment]
@micheltlutz creio que este lugar pode não ser um bom lugar para anunciar vagas.
Eu escrevi isso a algum tempo, veja se lhe é util:
https://gist.github.com/luzfcb/1c883b21ad2c2b456edb4a9a454a38b4

**Comment by micheltlutz** [comment]
Ok obrigado.
