### ISSUE TITLE
Estatuto desatualizado em alguns lugares

### ISSUE THREAD

**Issue by GabrielRF** [pythonbrasil/wiki#179]
O estatuto presente nos dois links abaixo está desatualizado. O segundo link foi indexado pelos buscadores e aparece no topo pra mim, por exemplo.

https://github.com/pythonbrasil/wiki/blob/2594ebb9ce101820e5592753a43aab30231a5d0b/content/pages/estatuto.rst

https://python.org.br/estatuto/

**Comment by humrochagf** [comment]
Done, atualizado conforme https://github.com/pythonbrasil/estatuto
