### ISSUE TITLE
[São Paulo] Cientista de Dados na BTG Pactual

### ISSUE THREAD

**Issue by ghost** [pythonbrasil/wiki#184]
####
A área de Data Analytics do BTG Pactual atende projetos de escopos variados com foco na transformação de dos datasets mais diversos em insights que agregam valor às nossas frentes de negócio. Há uma equipe enxuta e produtiva com total liberdade para experimentar diferentes técnicas e algoritmos de Machine Learning, bem como para aprender e utilizar diferentes linguagens e tecnologias.

Você fará análises exploratórias e geração de insights para o negócio; bem como desenvolverá modelos de Machine Learning.

###
Pátio Victor Malzoni – 14º Andar, Av. Brg. Faria Lima, 3477 – Itaim Bibi, São Paulo – SP, 04538-133

### Vale refeição/alimentação
Bônus de desempenho
Vale transporte
Assistência médica
Assistência odontológica

### Obrigatórios:
Formação completa
Conhecimento em Data Science e/ou Machine Learning
Pythonic Skills

### Desejáveis:
Experiência com TensorFlow ou outras bibliotecas de ML, Spark, R, serviços AWS;
Perfil data thirsty, analítico e empreendedor

###
CLT | Remuneração à combinar | **PRESENCIAL**

###
[Acesse o link](http://bit.ly/33ySgea)

![LK_BTG_DATA-SCIENTIST](https://user-images.githubusercontent.com/52975435/62973756-1e9cc480-bded-11e9-9dae-1916349e5bcd.png)

**Comment by luzfcb** [comment]
@carolinamedrado acho que aqui pode não ser um dos melhores lugares para publicar.
Seu anuncio, no geral está bom o suficiente, embora se fosse eu, eu deixaria explicito se aceita trabalho remoto ou se é somente presencial.

Eu listo mais alguns bons lugares para anunciar em

https://gist.github.com/luzfcb/1c883b21ad2c2b456edb4a9a454a38b4

**Comment by ghost** [comment]
> @carolinamedrado acho que aqui pode não ser um dos melhores lugares para publicar.
> Seu anuncio, no geral está bom o suficiente, embora se fosse eu, eu deixaria explicito se aceita trabalho remoto ou se é somente presencial.
> 
> Eu listo mais alguns bons lugares para anunciar em
> 
> https://gist.github.com/luzfcb/1c883b21ad2c2b456edb4a9a454a38b4

Obrigada pelo feedback! Já atualizei o anúncio, a vaga é presencial. Estou dando uma lida no link!

**Comment by adorilson** [comment]
@luzfcb atualmente, existem 3 issues de anuncio de vagas. O que você acha de fecharmos e trabalharmos na issue #37 ?

**Comment by cadu-leite** [comment]
Este ticket está fora de contexto.
A vagas pode ser anunciadas na lista de discussão Python
em https://groups.google.com/forum/#!forum/python-brasil

Ou vocês podem contribuir para que tenhamos uma página no site para publicação de vagas Python ... Que tal um PR?

Até lá este ticket não faz sentido.
OBrigado pelo interesse em nosso site
