### ISSUE TITLE
Atualizar content/pages/instalacao-windows.md

### ISSUE THREAD

**Issue by adorilson** [pythonbrasil/wiki#195]
content/pages/instalacao-windows.md referencia Python 3.4. Acredito que possa ser atualizado para a versão mais recente ou mesmo ficar de forma genérica. Além disso, e principalmente, as imagens estão com links quebrados.  Sem falar que as telas estão em inglês.

Update: na verdade, os links quebrados são apenas na visualização do arquivo no github. Em produção e localmento com "make serve" as imagens são apresentadas corretamente. Poderia ser melhorado a consistência.

**Comment by vinebarbosa** [comment]
Estou trabalhando nisso.

**Comment by vinebarbosa** [comment]
Feito!
