### ISSUE TITLE
Pagina EMPRESAS está quebrada

### ISSUE THREAD

**Issue by cadu-leite** [pythonbrasil/wiki#216]
URL: https://python.org.br/empresas/

Aceitei um pull request de "simplificação do código"

verificar se este PR quebrou o site - https://github.com/pythonbrasil/wiki/pull/206

OU conflitou com outra alteração

**Comment by cadu-leite** [comment]
@jtemporal e @fecaridade  podem me ajudar a verificar se foi realmente o merge da PR de vocês que quebrou ?

**Comment by cadu-leite** [comment]
**aparentemente** um problema com o famigerado `decode`

```bash
File "empresas_generator.py", line 26, in scrapping_empresas
```

```python
    file = file.read().decode()
```

```bash
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 30: ordinal not in range(128)
```
não tá rolando e pegando direto o arquivo json especificado no path nas lisnhas acima. (PARECE!)

**Comment by jtemporal** [comment]
acho que o @fecaridade como autor do código pode te ajudar @cadu-leite

**Comment by jtemporal** [comment]
@cadu-leite tenta dar revert no pr e refazer o build =)

**Comment by filipecifali** [comment]
Meu navegador (Firefox latest) não está carregando nada, as requisições já terminaram e falta todo conteúdo de css aparentemente.

![Screenshot_2019-11-25 Python Brasil(1)](https://user-images.githubusercontent.com/975041/69545747-25e97780-0f71-11ea-9900-164304d416a8.png)

**Comment by cadu-leite** [comment]
EM partes ... 

1 - deletaram o `pybr.min.css` e não deram rebuild ou colocaram o css em outro lugar. 
Não entendi o PR da @fecaridade .

2 - Depois de adicionar o arquivo citado, está dando erro no `Makefile:79: recipe for target 'import_empresas' failed`


Erro no travis: https://travis-ci.org/pythonbrasil/wiki/builds/616723968?utm_source=github_status&utm_medium=notification

ou erro travis aqui ...

```bash
python empresas_generator.py

Traceback (most recent call last):

  File "empresas_generator.py", line 57, in <module>

    for empresa in scrapping_empresas():

  File "empresas_generator.py", line 30, in scrapping_empresas

    for line in file.split('\n'):

TypeError: a bytes-like object is required, not 'str'

Makefile:79: recipe for target 'import_empresas' failed

make: *** [import_empresas] Error 1

The command "make html" exited with 2.

```

**Comment by cadu-leite** [comment]
localmente não consigo ver nada disso. 
Estou tendo que commitar e testar no commit. 
tem alguma outra "coisa"  pegando

**Comment by cadu-leite** [comment]
> EM partes ...
> 
> 1 - deletaram o `pybr.min.css` e não deram rebuild ou colocaram o css em outro lugar.
> Não entendi o PR da @fecaridade .
> 
> 2 - Depois de adicionar o arquivo citado, está dando erro no `Makefile:79: recipe for target 'import_empresas' failed`
> 
> Erro no travis: https://travis-ci.org/pythonbrasil/wiki/builds/616723968?utm_source=github_status&utm_medium=notification
> 
> ou erro travis aqui ...
> 
> ```shell
> python empresas_generator.py
> 
> Traceback (most recent call last):
> 
>   File "empresas_generator.py", line 57, in <module>
> 
>     for empresa in scrapping_empresas():
> 
>   File "empresas_generator.py", line 30, in scrapping_empresas
> 
>     for line in file.split('\n'):
> 
> TypeError: a bytes-like object is required, not 'str'
> 
> Makefile:79: recipe for target 'import_empresas' failed
> 
> make: *** [import_empresas] Error 1
> 
> The command "make html" exited with 2.
> ```

Não deletaram nada, 
o build está falhando por causa da função ligada a empresa, e por isso não builda o *static* e o que está online não acha o `css`. Por isso o site perdeu a formatação. Na verdade o build quebrou e não tem nada sendo gerado

**Comment by fecaridade** [comment]
@cadu-leite, estava vasculhando o pybr.min.css pois precisava descobrir o código ASCII de um Globo que utilizei para adicionar um Link para o planet Python, acabei deletando o arquivo para vê como ele se comportava e fiz isso em 2 Branch e acabei me atrapalhando e enviando a com a branch sem o py.min.css

**Comment by cadu-leite** [comment]
> @cadu-leite, estava esperando o pybr.min.css pois precisava descobrir o código ASCII de um Globo que utilizei para adicionar um Link para o planet Python, acabei deletando o arquivo para vê como ele se comportava e fiz isso em 2 Branch e acabei me atrapalhando e enviando a com a branch sem o py.min.css

relaxa @fecaridade  ...   eu ainda acho que não é só isso. Baseado no relatório do travis, 
tem uma **exception** que não deixa rodar o **build** . Isso está quebrando tudo !

**Comment by adorilson** [comment]
@cadu-leite qual é a versão do Python no servidor do Travis?

**Comment by cadu-leite** [comment]
A boa notícia é que o site voltou... 
A má notícia é que perdemos alguns PRs 

--------------------------------------------

O HEAD está apontando para ...

@humrocha afcae82add97b91fd25b1d096e93b9b45ce33d16 MergePullRequest 25 set 2019

@rougeth  8d6cff6b28338fce804ec6bad89123f40bda922d  24 SET 2019

## Lista de PRs desfeitos

| Autor  |      Pull request link |
|----------|:-------------:|
| @anapolive | https://github.com/pythonbrasil/wiki/pull/214 |
| @sergiomario |   https://github.com/pythonbrasil/wiki/pull/210 |
| @fecaridade | https://github.com/pythonbrasil/wiki/pull/206  !Cuidado com este! |
| @Liebelts |  https://github.com/pythonbrasil/wiki/pull/199 |

**Comment by adorilson** [comment]
@cadu-leite, o #206 foi refeito neste outro #222.

Acredito que os demais possam ser mesclados novamente sem problemas.

**Comment by cadu-leite** [comment]
tem algum problema na página de empresas ? porque reabriu o ticket ?
não é só aceitar o PR?  o PR faz outra coisa .
Confirma pra mim , ou fecha o ticket @adorilson

**Comment by cadu-leite** [comment]
> @cadu-leite tenta dar revert no pr e refazer o build =)

@jtemporal desculpe, na correria hoje pulei sua msg... 

EU não consegui dar um `revert` propriamente. Não entendi porque. 
Acabei voltando no commit antes das PRs. 
Obrigado pela ajuda @jtemporal

**Comment by cadu-leite** [comment]
> @cadu-leite qual é a versão do Python no servidor do Travis?

não tenho idéia !  
eu ACHO até que colaborei no inicio mas quem fez tudo andar foi o Humberto...

**Comment by luzfcb** [comment]
> qual é a versão do Python no servidor do Travis?

Python 3.6

**Comment by adorilson** [comment]
> tem algum problema na página de empresas ? porque reabriu o ticket ?

Espero que agora não tenha mais. Foi mais para garantir que você 
(ou alguém) veria. (Não sei com funciona comentários em issue fechadas)

> não é só aceitar o PR? o PR faz outra coisa .
> Confirma pra mim , ou fecha o ticket @adorilson

Fechando.
