### ISSUE TITLE
Atualizar para Pelican 4.2.0

### ISSUE THREAD

**Issue by luzfcb** [pythonbrasil/wiki#226]
Atualmente, o projeto é travado no Pelican 3.6.
O Pelican 4.2.0 inclui muitas melhorias e simplificações, contudo, migrar exigirá revisar muita coisa, mas pode valer a pena para manutenção a longo prazo.

https://docs.getpelican.com/en/stable/changelog.html

**Comment by rougeth** [comment]
#266 atualizou a versão do Pelican para a mais recente.
