### ISSUE TITLE
[SÃO PAULO (com auxílio) - Data Engineer no QuintoAndar]

### ISSUE THREAD

**Issue by carolgdsouza** [pythonbrasil/wiki#234]
Eii, essa é pra você que **quer fazer parte do maior aplicativo de aluguel de imóveis do país** com uma equipe de primeira linha que usa as **melhores práticas e as melhores ferramentas** na empresa que está mudando a experiência do mercado imobiliário no Brasil.

**QuintoAndar** é uma empresa de tecnologia que permite uma experiência de aluguel ininterrupta, da descoberta ao contrato. Buscamos os melhores de talentos de **Data Engineer** que se identifiquem com o propósito e interesse em participar do movimento de crescimento da empresa, fazendo parte de um **projeto de alto impacto que afetará a vida de muitas pessoas.**

**SQL**, arquitetura de dados e modelos de dados relacionais e bancos de dados. **Python** (ou outras linguagens de script). Experiência anterior na construção de **data marts, data lake** e estruturação de um **data warehouse** e armazenamento em colunas (como o Amazon Redshift).

Contratação **CLT (Presencial em tempo integral) em São Paulo**, na R. Girassol, 555 – Vila Madalena. Outro escritório em Campinas. Disponibilidade de exportação.

https://intera.talent-hacking.com/quintoandar/data-engineer/

**Comment by rougeth** [comment]
Reportado como SPAM.
