### ISSUE TITLE
[SP/SP] Dev Python Sênior - 3 vagas [Source 2IT]

### ISSUE THREAD

**Issue by pamelapsi** [pythonbrasil/wiki#235]
**Source 2IT** contrata **3** profissionais na modalidade CLT para cliente na Granja Julieta, São Paulo/SP.
**contato:** pamela.miranda@source2it.com.br

Experiência com Python 3;
Experiência com Django e/ou Flask;
Experiência com desenvolvimento de microserviços, construção de API em Rest;
Conhecimento de serviços cloud:  AWS e Azure;
Conhecimento de DevOps
Conhecimento em versionamento GIT.

**Comment by rougeth** [comment]
Reportado como SPAM.
