### ISSUE TITLE
[SÃO PAULO- com auxilio] – Data Engineer Senior na Inspetor

### ISSUE THREAD

**Issue by carolgdsouza** [pythonbrasil/wiki#237]
A **Inspetor** precisa de você para fazer parte da construção da **mais moderna plataforma antifraude da América Latina.**

É tudo do início! Com a missão de garantir todo o ecossistema **antifraude para ecommerces** do Brasil, a Inspetor tem no **comando de sua operação referências no ramo de data**, os seus sócios fundadores são formados em **Stanford e com passagem pela Palantir Technology**. Uma equipe realmente sênior e com **exigência técnica elevada**, trazendo as principais novidades tecnológicas diretamente do ecossistema dos sócios.

**Oque esperamos de você?** Estamos em busca de talentos **Data Engineer Sênior** que se identifiquem com o propósito e interesse em participar do movimento de crescimento da empresa, compondo o seu time. Seja um líder no **desenvolvimento da infraestrutura de dados na Inspetor** tendo entre as responsabilidades de definir a arquitetura e construção do pipeline de dados; projetar e implementar melhorias nos processos internos.

**Python, AWS (Kinesis, Lambda, RDS), Ferramentas de processamento de dados open-source como Apache Spark, Airflow, Flink, ou frameworks similares.**

A contratação será feita em **CLT, remuneração acima de R$12.000 reais** com alocação **presencial** no Rua Joaquim Antunes, nº601, Pinheiros, São Paulo – SP

**Página da vaga:** https://vagas.byintera.com/inspetor/senior-data-engineer/

**Comment by rougeth** [comment]
Reportado como SPAM.
