### ISSUE TITLE
Corrigir dados da PythOnRio

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/wiki#296]
- [ ] Grupo do telegram -> https://t.me/pythonrio2023, não 
- [ ] Nome está incorreto: deveria ser PythOnRio e não PythonOnRio
- [ ] Remover google groups, talvez? Não creio que esteja sendo utilizado

**Comment by vitorsantanna2** [comment]
Issue conclúida, fiz os testes localmente, tudo certo.
Segue a PR: https://github.com/pythonbrasil/wiki/pull/297

**Comment by adorilson** [comment]
@biancarosa Já fiz o merge do PR. Dá uma conferida e fecha a issue, se for o caso.
