### ISSUE TITLE
Página sobre a lista de discussão não está mais funcionando

### ISSUE THREAD

**Issue by lskbr** [pythonbrasil/wiki#299]
Ao acessar:
https://python.org.br/lista-de-discussoes/

Aparece um erro:
Embedded groups are no longer supported. To view this group, visit [Google Groups](https://groups.google.com/d/forum/python-brasil). [Learn more](https://support.google.com/a/answer/9687393#deprecated)

**Comment by adorilson** [comment]
Acho que esse menu Lista de Discussões poderia ser substituida por "Redes sociais" e nele ser listado o que está na seção Social do rodapé.

**Comment by lskbr** [comment]
eu acho que antes era um frame do google groups para lista da Python Brasil.

**Comment by adorilson** [comment]
Duplica #265
