### ISSUE TITLE
página de eventos

### ISSUE THREAD

**Issue by humrochagf** [pythonbrasil/wiki#4]
Assim os eventos podem ser submetidos como postagens com descrição e página com mais informações

**Comment by diegorocha** [comment]
Uma postagem normal não resolve? Não entendi. Qual seria a customização ?

**Comment by humrochagf** [comment]
é mais quanto a formatação no tema, a troca de nomeclaturas de blog para eventos, nada de outro mundo não

**Comment by humrochagf** [comment]
aqui vamos usar o esquema json do @magnunleno e deixar o modelo de postagem pras vagas

**Comment by humrochagf** [comment]
done
