### ISSUE TITLE
reorganizar menu

### ISSUE THREAD

**Issue by humrochagf** [pythonbrasil/wiki#45]
Reorganizar o menu para melhor atender os novos objetivos

Eu sugiro aproveitar a idéia do site atual e abrigar os conteúdos como sub-itens das grandes frentes que são:
- Impressione-se
- Inicie-se
- Aprenda mais 
- Envolva-se

assim ganhamos espaço para funcionalidades no menu como a busca 
mas se alguém tiver uma idéia de estrutura de organização mais interessante pode apresentar aqui

**Comment by diegorocha** [comment]
Pode finalizar essa, não?

**Comment by humrochagf** [comment]
Então, ficou bom desta forma, se ninguém tiver nada a acrescentar vou fechar
