### ISSUE TITLE
Conteúdo de Inicie-se

### ISSUE THREAD

**Issue by humrochagf** [pythonbrasil/wiki#47]
Adicionar conteúdo de como instalar e rodar python nas diversas plataformas

**Comment by humrochagf** [comment]
É só editar usando markdown o arquivo:
https://github.com/pythonbrasil/wiki/blob/pelican/content/pages/inicie-se.md

**Comment by mazulo** [comment]
No caso seria passar o conteúdo [desta página](http://wiki.python.org.br/InicieSe), porém atualizado?

**Comment by humrochagf** [comment]
eh isso, mas pode adicionar mais coisa que condiz com quem está iniciando

minha idéia era depois quebrar este conteúdo em um inicie-se geral do python
e sub-páginas com inicie-se em python web, python game, python científico etc

**Comment by cadu-leite** [comment]
outra **sugestão**. O inicie-se não poderia ser o conteudo de aprendizado python. 
e criariamo uma página para o ..  
**instalando Python** ?

ou não ?

**Comment by humrochagf** [comment]
pode separar em sublink tb, tipo, dentro de inicie-se tem como instalar e conteúdo iniciante

**Comment by humrochagf** [comment]
criei as subpáginas para ficar mais fácil de intender a estrutura

**Comment by cadu-leite** [comment]
acho que ficou legal, se houver outras opiniões podemos ir fazendo aos poucos.

**Comment by rafaelhenrique** [comment]
Criei alguns posts no meu blog para inciantes, o conteúdo está todo em markdown (conforme mencionei em #61). Se vcs acharem legal posso contribuir com este conteúdo lá (após estar definida a estrutura que ficará). :wink:

**Comment by gutierri** [comment]
Podemos manter a página como da antiga wiki, separar as coisas por seção e já no começo dar uma introdução básica sobre Python ou colocar um parágrafo pequeno com um link para a página de aprendamais (  #48 ), algo como a página do "[Beginner's Guide to Python](https://wiki.python.org/moin/BeginnersGuide)".

**Comment by filipecifali** [comment]
@rafaelhenrique queremos sim! Pode tacar ficha e se necessário, mudamos depois a estrutura das páginas.

@gutierri É uma boa, você pode começar essa página?

**Comment by rafaelhenrique** [comment]
valeu @filipecifali ... fico satisfeito em poder ajudar :smile: ... assim que possível vou fazer :wink:

**Comment by gutierri** [comment]
@filipecifali Vou separar algumas horas do fim de semana e posso começar ajudar nisso, sim.

**Comment by adorilson** [comment]
Isso está feito? Issue por ser fechada?
