### ISSUE TITLE
Documentação de como contribuir

### ISSUE THREAD

**Issue by humrochagf** [pythonbrasil/wiki#5]
Atualizar o README para informar como contribuir com conteúdo, programação e design

**Comment by magnunleno** [comment]
Deixa essa comigo!

**Comment by humrochagf** [comment]
:+1:

**Comment by diegorocha** [comment]
Essa issue pode ser fechada, não? Acho que o readme e os scripts estão bem completos agora

**Comment by humrochagf** [comment]
Falta a descrição pra quem não é programador, falando os arquivos que podem ser editados para alterar o conteúdo

**Comment by cadu-leite** [comment]
Eu tenho uma idéia diff...  

O arquivo README poderia conter 
1.  _conteúdo X arquivo_
2. Links para a WIKI do projeto com páginas de doc detalhados. 

Minha idéia era ter um README mais suscinto onde um não programador se sinta a vontade de ler, e utilizar as páginas do WIKI para detalhar outras possibilidades de contribuições, detalhes mais técnicos.

**Comment by humrochagf** [comment]
@cadu-leite atualizei lá com o mapeamento

**Comment by cadu-leite** [comment]
tá ok pra mim. se quiserem pode fechar. Acho que agora seriam issues mis pautadas em cada ponto do conteúdo.

**Comment by humrochagf** [comment]
:+1:
