### ISSUE TITLE
Páginas Secundárias

### ISSUE THREAD

**Issue by cadu-leite** [pythonbrasil/wiki#60]
Sugestão de retirar o

 _"banner: A comunidade Python Brasil reune grupos de usuários em todo o Brasil interessados em difundir e divulgar a linguagem de programação."_ 

nas páginas secundárias. 
teriamos um _template_ pra _Home_ e um para _**outras páginas**_
de modo que o conteúdo das outras páginas fique em evidência mais fácil de ler.

**Comment by humrochagf** [comment]
@cadu-leite retirei o banner por completo nas páginas que não são a home para ficar mais content driven, vê lá se ficou legal

**Comment by cadu-leite** [comment]
perfect.
