### ISSUE TITLE
Conteúdo de tutoriais para iniciantes.

### ISSUE THREAD

**Issue by cadu-leite** [pythonbrasil/wiki#61]
Minha idéia aqui POR HORA não é bem uma issue mas um local para juntarmos conteúdo **atualizado** e em **pt-BR** para sugerir para os iniciantes em Python.

Para contribuir:
1 - comentar a issue com uma sugestão, informando Link, autor, e se possível a data da edição 
2 - Forkar o projeto e contribuir direto na página da wiki

**Comment by cadu-leite** [comment]
## _Idéia de modelo para add info na página_

## Python

### FREE Na WEB

| nível | data | Título | Autor | Link |
| --- | --- | --- | --- | --- |
| iniciante |  | Python para Zumbis | Masanori | [Curso](http://pycursos.com/python-para-zumbis/) |
| iniciante |  | Vídeos Python para Zumbis | Masanori | [PlayList Python para Zumbis](https://www.youtube.com/playlist?list=PLUukMN0DTKCtbzhbYe2jdF4cr8MOWClXc) |
| iniciante | 2016 | video PyLadies BH | Pyladies BH | [Video PyLadies](https://www.youtube.com/watch?v=O2xKiMl-d7Y) |
| iniciante | 2016 | Aulas Python | Pedro Forli | [video aulas Python](https://www.youtube.com/playlist?list=PLfCKf0-awunOu2WyLe2pSD2fXUo795xRe) |

### Livros

| nível | data | Título | Autor | Link | loja |
| --- | --- | --- | --- | --- | --- |
| iniciante |  | Introdução à Programação com Python | Nilo Ney Coutinho Menezes | [link](http://python.nilo.pro.br/) |  |
| intermediário | 2015/2016 | Python Fluente | Luciano Ramalho | [Liv. Cultura](http://www.livrariacultura.com.br/p/python-fluente-46122207) |  |

## Django

### FREE Na WEB

| nível | data | Título | Autor | Link |
| --- | --- | --- | --- | --- |
| iniciante | 2015 | Tutorial Django Girls | Django Girls | http://tutorial.djangogirls.org/pt/ |

### Livros

| nível | data | Título | Autor | Link | loja |
| --- | --- | --- | --- | --- | --- |
|  |  | -------- | ------- | ------ | ------- |

## Flask

### FREE Na WEB

| nível | data | Título | Autor | Link |
| --- | --- | --- | --- | --- |
| todos | 2015 | What The Flask | Bruno Rocha | http://pythonclub.com.br/tag/what-the-flask.html |

### Livros

| nível | data | Título | Autor | Link | loja |
| --- | --- | --- | --- | --- | --- |
|  |  | -------- | ------- | ------ | ------- |

## Outros Frameworks & Bibliotecas

### FREE Na WEB

| nível | data | Título | Autor | Link |
| --- | --- | --- | --- | --- |
|  |  | -------- | ------- | ------ |

### Livros

| nível | data | Título | Autor | Link | loja |
| --- | --- | --- | --- | --- | --- |
|  |  | -------- | ------- | ------ | ------- |

**Comment by michel-rodrigues** [comment]
nível: Iniciante
data:
Título: Aulas Python
Autor: Pedro Forli
Link: https://www.youtube.com/playlist?list=PLfCKf0-awunOu2WyLe2pSD2fXUo795xRe

**Comment by rafaelhenrique** [comment]
| nivel | data | titulo | autor | link |
| --- | --- | --- | --- | --- |
| iniciante | 04/04/2016 | O que são métodos/funções in-place no Python? | Rafael Henrique da Silva Correia | http://blog.abraseucodigo.com.br/o-que-sao-metodos-funcoes-inplace-no-python.html |
| iniciante | 24/02/2016 | Instalando qualquer versão do Python no Linux/Mac OSX utilizando pyenv | Rafael Henrique da Silva Correia | http://blog.abraseucodigo.com.br/instalando-qualquer-versao-do-python-no-linux-macosx-utilizando-pyenv.html |
| iniciante | 23/02/2016 | Python uma linguagem de tipagem dinâmica e forte | Rafael Henrique da Silva Correia | http://blog.abraseucodigo.com.br/python-uma-linguagem-de-tipagem-dinamica-e-forte.html |
| iniciante | 17/02/2016 | virtualenv/pip pra que servem? | Rafael Henrique da Silva Correia | http://blog.abraseucodigo.com.br/virtualenv-pip-pra-que-servem.html |
| iniciante | 16/02/2016 | Instalando Python 3.5 no Windows 7 | Rafael Henrique da Silva Correia | http://blog.abraseucodigo.com.br/instalando-python35-no-windows-7.html |

Também estou gravando as aulas do Grupo de Estudos Python de Sorocaba, mas preciso indexar por assunto para facilitar para quem vai assistir. Os vídeos estão aqui:

https://www.youtube.com/playlist?list=PL6f2gQ2RXLosWiXDHM7vOr1MPdfxPAm_t

Vou criar um post no blog logo logo para organizar esta bagunça. Este conteúdo do Blog está em markdown caso precise mudar ou publicar em outro lugar :smile:. 

Espero que este conteúdo ajude. Se eu souber de outros posto aqui. Pelo que vi na Wiki ainda não tem documento de instalação do Python, ficaria muito satisfeito em poder contribuir com isso.

**Comment by gutierri** [comment]
Na Wiki ficaria uma lista de links? Não parece muita coisa para trilhar o caminho dos iniciantes? Eu gostaria de começar a preencher o wiki com isso, mas estou confuso. Poderiamos dar uma filtrada no que parece mais interessante, importante e claro para quem quer começar, talvez informação demais só gere mais confusão.

**Comment by humrochagf** [comment]
Sim seria interessante na página principal do inicie-se ter um conteúdo mais selecionado, com os cursos e livros online mais indicados e meio que uma descrição rápida deles tipo o python para zumbis, de preferência que preencha requisitos como:
- estar em português;
- ser introdutório a linguagem e não a uma ferramenta específica;
- não ser tutorial e sim um curso/livro com inicio meio e fim;
- com um objetivo claro;
- etc.

E aí em sub-páginas referências a temas mais específicos como:
- introdução a python para web;
- introdução a python para big data;
- mobile;
- games;

A abordagem para demonstrar isso podemos discutir aqui, quem tiver uma idéia seria legal fazer um fork e demonstrar, se surgir uma idéia massa com certeza vai ser incorporada a wiki :smiley:

**Comment by jtemporal** [comment]
As PyLadies estão no processo de organizar todos os materiais que possuímos para colocar num lugar centralizado, seria ótimo que a lista daqui fosse complementada com a lista de lá. E vice versa na minha opinião.

**Comment by alisonamerico** [comment]
nível: Do **Iniciante** até onde sua curiosidade for...("Não é só um blog para ensino da linguagem, mas mostra tudo sobre a comunidade Python, principalmente no Brasil.")
data: 16/12/2015 (data desse post)
Título: Aprendendo Python (Guia para iniciantes a programação em Python)
Autor: Eric Hideki
Link: https://ericstk.wordpress.com/2015/02/16/guia-para-iniciantes-a-programacao-em-python/

nível: Do **Iniciante** até onde sua curiosidade for...
data:
Título: Python - Aprenda a programar em Python de forma descomplicada.
Autor: Eric Hideki
Link: http://www.devfuria.com.br/python/

**Comment by gilsondev** [comment]
Tem também a tradução do Pycubator: df.python.org.br/pycubator/

**Comment by adorilson** [comment]
Olá, @cadu-leite. 

Estou mentorando estudantes nesse [Hacktoberfest 2019](https://github.com/adorilson/hacktoberfest-ifrn-cm).

Um dos repos que elegi como candidato para os PRs foi este,
sendo uma das propostas melhorar a seção "Indicação de cursos" da página [Introdução](https://python.org.br/introducao/).  Que é fazer exatamente essa organização que você fez.

Você disse 

> Para contribuir:
> 1 - comentar a issue com uma sugestão, informando Link, autor, e se possível a data da edição
> 2 - Forkar o projeto e contribuir direto na página da wiki

A ideia era colocar esse conteúdo daqui lá na página de Introdução?

Também concordo com a ideia do @humrochagf, exceto pelo tutorial, que poderíamos abrir uma exceção para o Tutorial (oficial) do Python. As sub-páginas que ele citou podem ser no menu Aprender mais.
