### ISSUE TITLE
Criar pagina com informações sobre PyLadies e Django Girls

### ISSUE THREAD

**Issue by luzfcb** [pythonbrasil/wiki#66]
Seria bom criar uma pagina para listar os grupos das PyLadies e Django Girls espalhados pelo pais, ou inclui-las no pagina de grupos locais e tambem citar o que são e quais os objetivos.

**Comment by humrochagf** [comment]
Acho legal listar em uma página separada mesmo seguindo a mesma lógica dos grupos pq como o pyladies é tão numeroso quanto os grupys ficaria meio confuso, e é legal tb que aí dá para colocar uma descrição sobre a iniciativa e talz

**Comment by luzfcb** [comment]
@humrochagf seria bom marcar nessa issue, algumas das mulheres ativas nos grupos PyLadies.

**Comment by humrochagf** [comment]
pronto subi uma página para o pyladies, agora vou entrar em contato com elas

**Comment by humrochagf** [comment]
Pronto, vou manter essa issue aberta para auxiliar quem tiver alguma dúvida

**Comment by jtemporal** [comment]
@pgrangeiro @izaguerreiro @taniaa @leportella @saletefarias

**Comment by filipecifali** [comment]
Acredito que a melhor estratégia seja buscar os dados de um site específico que o grupo alimente, porque dai não precisa duplicar a informação, apesar de se tornar uma dependência. 

Algo como pyladies/api/groups retornar uma lista e essa lista gerar o conteúdo da página, não sei se o Pelican vai ter suporte, mas seria o mais prático, se não, adicionamos burocracia e a chance de "esquecimento" não intencional.

**Comment by jtemporal** [comment]
As PyLadies estão trabalhado no nosso site, pra reformular algumas coisas, gostaria de ajudar nisso, tbm usamos pelican. Se tiver algo q possamos fazer pra ajudar pra fazer uma integração mais fácil, criar a api ou coisa do gênero. Podem abrir issues lá no nosso repo pra gnt acelerar isso :)

https://github.com/pyladies-brazil/br-pyladies-pelican

**Comment by filipecifali** [comment]
@jtemporal criei uma issue lá https://github.com/pyladies-brazil/br-pyladies-pelican/issues/112 para fazer a conexão :+1:

**Comment by jtemporal** [comment]
@filipecifali a paulinha [respondeu](https://github.com/pyladies-brazil/br-pyladies-pelican/issues/112#issuecomment-255370961) ...  e a issue foi fechada.

**Comment by luzfcb** [comment]
em relação a parsear o arquivo https://github.com/pyladies-brazil/br-pyladies-pelican/blob/master/data/locations.yml indicado pela @pgrangeiro 

Para manter simples as pessoas contribuírem com este repositório (mesmo se estiverem usando Windows), eu sugiro quem for fazer a integração (consumir o arquivo yml), a utilizar o https://github.com/hackebrot/poyo em vez do PyYAML, porque o PyYAML tem vários bugs em relação a Windows...

O `poyo` é feito em python puro, e implementa parte da especificação YAML. Ele foi criado para o projeto cookiecutter, para resolver os vários problemas de compatibilidade com Windows que o PyYAML possui...

**Comment by muriloviana** [comment]
Acredito que o fato do Pelican gerar páginas estáticas, não seja possível criar uma API como o @filipecifali sugeriu (o que seria ideal).

Fiz um PR #97 , com a ajuda do @edussilva, para adicionar um comando (`make import_pyladies`) que importa os dados do site das Pyladies para gerar os arquivos JSON, no repositório correspondente ao seu conteúdo.

Desta forma, após adicionar uma nova sede no site das Pyladies, bastaria dar o comando `make import_pyladies` para importar os dados, e depois gerar um novo output através do comando `make html`.

Esta é apenas uma sugestão, estou aberto a novas ideias.

**Comment by humrochagf** [comment]
Testado e integrado ao deploy obrigado pela ajuda @muriloviana

**Comment by humrochagf** [comment]
Mais alguma pendencia nesta issue?

**Comment by filipecifali** [comment]
Como já está automatizado, estamos no cenário ideal onde não precisa de intervenção humana para atualizar o site, caso necessário abrimos outra issue, mas a princípio está resolvido, muito obrigado a todos pela colaboração!

**Comment by luzfcb** [comment]
@filipecifali pelo que entendi, na verdade não está totalmente automatizado, porque é necessário rodar o "import_pyladies" a cada build. Se houver modificações no conteúdo delas, não tem como saber-mos de maneira automática. (talvez implementar hook para o github resolva..) (não testei o código, posso estar falando besteira)

**Comment by humrochagf** [comment]
teria que fazer o repositório das pyladies acionar o deploy no travis do python brasil, mas como nem toda atualização no site do pyladies influencia no repo python brasil, não sei se precisa de fazer isso não, todo  push nesse repo já atualiza as infos do pyladies, creio que seja suficiente

**Comment by muriloviana** [comment]
O que o @luzfcb disse está correto. Porém, como o @humrochagf comentou, se todo push nesse repo já atualiza as infos do pyladies, acredito que a pendência desta issue está resolvida 😃 .
