### ISSUE TITLE
Estruturar página comunidade

### ISSUE THREAD

**Issue by humrochagf** [pythonbrasil/wiki#7]
Ajustar o tema para fazer uma listagem das comunidades regionais com informações como 
- Nome do grupo
- Cidade
- Estado
- Site
- Github
- Lista de emails
- etc...

**Comment by luzfcb** [comment]
talvez seja uma boa hora de pensarmos em dar uma geral no http://pythonpeople.znc.com.br/ e criar uma view que renderiza um template especificamente formatado para ser integrado via iframe, como foi feito com o Google Groups

**Comment by humrochagf** [comment]
hehehe, então eu estava mexendo nele a uns dias atrás.

Atualizando pra django 1.8 pra poder preparar ele pra ficar mais fácil de contribuir, mas agarrei em um erro no syncdb relacionado ao postgis que não estou conseguindo solucionar, a branch é essa https://github.com/humrochagf/python-people/tree/django-1.8

**Comment by erichideki** [comment]
Estou listando todos os grupos de usuários já. 

Já mando o PR com essas informações.

Quanto ao Python people, vai na manha Humberto, faz com calma isso e, se der, implementamos isso.

"Simples é melhor que complexo" :)

**Comment by humrochagf** [comment]
SIm, a parada do python people algo que eu fiz durante o sprint da python brasil, não é algo que eu vá dar prioridade agora não, só publiquei pq se alguém manjar e quiser fuçar lá pode ficar a vontade :stuck_out_tongue_winking_eye:

**Comment by humrochagf** [comment]
@luzfcb tem alguma forma de passarmos como atributo do [comunidade.md](https://github.com/pythonbrasil/apyb/blob/pelican/content/pages/comunidade.md) a listagem dos grupys de forma estruturada, tipo um json pra podermos montar um template legal sobre estes dados?

**Comment by luzfcb** [comment]
@LucasMagnum como vc implementou algo parecido no pythonclub, alguma ideia sobre a pergunta do @humrochagf ?

**Comment by LucasMagnum** [comment]
@luzfcb @humrochagf acho que dá pra criar um plugin do pelican pra fazer isso. 

No pythonclub eu pego todos os `articles` e monto um `json`.  [-> Link <- ](https://github.com/LucasMagnum/pythonclub.github.io/blob/pelican/custom-plugins/json_articles/json_articles.py)

**Comment by humrochagf** [comment]
resolvido em #33
