### ISSUE TITLE
Dúvida - replicar conteúdo da wiki http://wiki.python.org.br/PythonBrasil

### ISSUE THREAD

**Issue by cantoniazzi** [pythonbrasil/wiki#86]
Esse novo site tem quase a mesma arquitetura de informação da wiki antiga da Python Brasil (http://wiki.python.org.br/PythonBrasil)

Podemos copiar grande parte do conteúdo da wiki antiga e colocar nessa nova? Estou perguntando, porque acabei de fazer isso colocando conteúdo na página das ferramentas (criei um pullrequest e coloquei a referência).

**Comment by filipecifali** [comment]
@cantoniazzi Acabei demorando pra fazer o merge inicial das PRs mas agora vai ser mais rápido!
